instructions:
  nop: 0x00
  lda: 0x10
  sta: 0x20
  jmp: 0x30
  add: 0x40
  sub: 0x41
  mul: 0x42
  cmp: 0x43
  and: 0x44
  or:  0x45
  sla: 0x46
  sra: 0x47
  slax: 0x48
  srax: 0x49
  hlt: 0x01
memory:
  size: 256
  addr size: 2
  op size: 2
  address then instruction: false
